#!/bin/bash

[ -z "$DJ_URL" ] && DJ_URL='http://localhost:9000'

function play() 
{
	curl -X POST -o /dev/null $DJ_URL/commands/play -s
	echo "Playing the queue on $DJ_URL/commands/play"
	return;
}

function stop() 
{
	curl -X POST -o /dev/null $DJ_URL/commands/stop -s
	echo "Stopping the queue on $DJ_URL/commands/stop"
	return;
}

function next() 
{
	curl -X POST -o /dev/null $DJ_URL/commands/next -s
	echo "Nexting the queue on $DJ_URL/commands/next"
	return;
}

function clear() 
{
	curl -X POST -o /dev/null $DJ_URL/commands/clear -s
	echo "Clearing the queue on $DJ_URL/commands/clear"
	return;
}

function monitoring()
{
	curl $DJ_URL/monitoring
	return;
}

function updtplaying()
{
	curl -X POST -o /dev/null $DJ_URL/commands/updtplaying -s
	echo "Update playing on $DJ_URL/commands/updtplaying"
	return;
}

function updtlist()
{
	curl -X POST -o /dev/null $DJ_URL/commands/updtlist -s
	echo "Update library list on $DJ_URL/commands/updtlist"
	return;
}

function say()
{
    MESSAGE=$1
    echo $MESSAGE
    MESSAGE=`echo $MESSAGE | tr ' ' '%20'`
	curl -X POST -d "message=$MESSAGE" -o /dev/null $DJ_URL/commands/say -s
	echo "Pushing message '$MESSAGE' to all clients on $DJ_URL/commands/say"
	return;
}

function echoStart()
{
	echo "|================== DJ ====================|"
	echo " "
	return;
}

function displayHelp()
{
    echo " "
    echo "|==========================================|"
    echo "|                                          |"
    echo "|             Welcome in DJ !!!            |"
    echo "|                                          |"
    echo "|==========================================|"
    echo " "
    echo "You're targetting DJ server @ $APP_PATH "
    echo " "
	echo "You can use the following commands :"
	echo " "
	echo "  play        play the first song in the queue"
	echo "  stop        stop the current song"
	echo "  next        skip to next song"
	echo "  clear       clear the current queue"
	echo "  monitoring  display montoring stream"
	echo "  say %       broadcast text message on all client"
	echo "  updtlist    update library on all clients"
	echo "  updtplaying update playing sidebar on all clients"
	echo "  --help      display help"
	echo " "
	echo "Have fun :)"
	echo " "
	return;
}

case $1 in
 play)
  echoStart
  play $2
  ;;
 stop)
  echoStart
  stop $2
  ;;
 next)
  echoStart
  next $2
  ;;
 clear)
  echoStart
  clear $2
  ;;
 monitoring)
  echoStart
  monitoring $2
  ;;
 say)
  echoStart
  say $2
  ;;
 updtlist)
  echoStart
  updtlist $2
  ;;
 updtplaying)
  echoStart
  updtplaying $2
  ;;
 --help)
  displayHelp
  ;;
 *)
  #echo "display the help :)"
  ;;
esac

#complete -F _completion -o filenames dj
